name: Cron to update articles database
on:
  schedule:
    - cron: "* * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install Scrapy
          python -m pip install itemadapter
          python -m pip install pymongo
          python -m pip install python-dotenv
          python -m pip install textblob

      - name: CRON JOB
        env:
          MONGO_URI: ${{secrets.MONGO_URI}}
        run: |
          echo "${{ secrets.TEST_VALUE }}"
          scrapy crawl article
